import json
import shlex
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml


def register_schema(schema_name: str, schema_path: Path) -> None:
    try:
        from dawn.runtime import schemas as runtime_schemas
    except ImportError:
        return

    if schema_name in runtime_schemas.SCHEMA_REGISTRY:
        return

    if not schema_path.exists():
        return

    with schema_path.open("r") as fh:
        schema_data = json.load(fh)

    runtime_schemas.SCHEMA_REGISTRY[schema_name] = schema_data


def load_artifact(artifact_store, artifact_id: str) -> Dict[str, Any]:
    meta = artifact_store.get(artifact_id)
    if not meta:
        raise RuntimeError(f"Missing artifact {artifact_id}")
    with open(meta["path"], "r") as fh:
        return json.load(fh)


def escape_literal(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_command(unit: Dict[str, Any], level: str) -> str:
    path = unit.get("entrypoint") or unit.get("path") or "."
    quoted = shlex.quote(path)
    base_name = unit.get("id", "unknown").split(".")[-1]
    if unit["type"] == "module":
        if level == "L0_contract":
            return f"python3 -m pytest artifacts/forgescaffold.test_matrix/test_harness/tests/test_l0_smoke.py"
        if level == "L1_slice":
            return f"python3 -m pytest {quoted}"
        if level == "L2_smoke":
            return f"python3 {quoted}"
        return f"echo \"Collect L3 metrics for {unit['id']}\""
    if unit["type"] == "service":
        clean = escape_literal(path)
        if level == "L0_contract":
            return f"python3 -c 'import os; print(\"service file exists\", os.path.exists(\"{clean}\"))'"
        if level == "L1_slice":
            return f"python3 -c 'import os, json; print(\"service config\", os.path.exists(\"{clean}\"))'"
        if level == "L2_smoke":
            return f"echo \"simulate HTTP call to {base_name}\""
        return f"echo \"collect nonfunctional metrics for {base_name}\""
    if unit["type"] == "agent_step":
        if level == "L0_contract":
            return f"python3 -m compileall {quoted}"
        if level == "L1_slice":
            return f"python3 {quoted}" if unit.get("entrypoint") else f"echo \"run stub for {base_name}\""
        if level == "L2_smoke":
            return f"echo \"simulate agent run for {base_name}\""
        return f"echo \"audit agent metrics for {base_name}\""
    if unit["type"] == "datastore":
        clean = escape_literal(path)
        if level == "L0_contract":
            return f"python3 -c 'import os; print(\"datastore access\", os.path.exists(\"{clean}\"))'"
        if level == "L1_slice":
            return f"echo \"backup datastore schema for {base_name}\""
        if level == "L2_smoke":
            return f"echo \"run sample read/write against {base_name}\""
        return f"echo \"verify SLA hooks for {base_name}\""
    if unit["type"] == "external_dependency":
        import_name = base_name.replace("-", "_")
        if level == "L0_contract":
            return f"python3 -c 'import {import_name}; print(getattr({import_name}, \"__version__\", \"unknown\"))'"
        if level == "L1_slice":
            return f"echo \"validate {import_name} compatibility\""
        if level == "L2_smoke":
            return f"echo \"link {import_name} into glue layer\""
        return f"echo \"audit security posture for {import_name}\""
    return f"echo \"Level {level} for {unit['id']}\""


def write_harness(sandbox, language: str) -> Dict[str, Any]:
    harness_root = Path("test_harness")
    files = []

    readme = (
        "# ForgeScaffold Test Harness\n\n"
        "This harness is generated by forgescaffold.test_matrix.\n\n"
        "## Run (Python)\n\n"
        "```bash\n"
        "python3 -m pytest artifacts/forgescaffold.test_matrix/test_harness/tests\n"
        "```\n\n"
        "## Run (Node)\n\n"
        "```bash\n"
        "node --test artifacts/forgescaffold.test_matrix/test_harness/node_tests\n"
        "```\n"
    )
    readme_path = sandbox.write_text(str(harness_root / "README.md"), readme)
    files.append({"path": "test_harness/README.md", "kind": "doc"})

    if language == "python":
        test_dir = harness_root / "tests"
        test_content = (
            "def test_l0_smoke():\n"
            "    assert True\n"
        )
        test_path = sandbox.write_text(str(test_dir / "test_l0_smoke.py"), test_content)
        files.append({"path": "test_harness/tests/test_l0_smoke.py", "kind": "test"})
    elif language == "node":
        test_dir = harness_root / "node_tests"
        test_content = (
            "import assert from 'node:assert/strict';\n\n"
            "test('l0 smoke', () => {\n"
            "  assert.equal(true, true);\n"
            "});\n"
        )
        sandbox.write_text(str(test_dir / "test_l0_smoke.js"), test_content)
        files.append({"path": "test_harness/node_tests/test_l0_smoke.js", "kind": "test"})

    manifest = {
        "root": "test_harness",
        "language": language,
        "files": files,
    }
    manifest_path = sandbox.publish(
        "forgescaffold.test_harness.manifest.json",
        str(harness_root / "manifest.json"),
        manifest,
        schema="json",
    )
    return {"manifest": manifest, "manifest_path": manifest_path}


def run(project_context: Dict[str, Any], link_config: Dict[str, Any]) -> Dict[str, Any]:
    project_root = Path(project_context["project_root"])
    sandbox = project_context.get("sandbox")
    artifact_store = project_context.get("artifact_store")
    if not sandbox or not artifact_store:
        raise RuntimeError("Sandbox or artifact store missing")

    schema_path = Path(__file__).resolve().parents[2] / "schemas" / "test_matrix.schema.json"
    register_schema("forgescaffold.test_matrix", schema_path)

    catalog = load_artifact(artifact_store, "forgescaffold.system_catalog.json")
    dataflow = load_artifact(artifact_store, "forgescaffold.dataflow_map.json")

    units = sorted(catalog.get("units", []), key=lambda u: u.get("id"))
    languages = sorted({unit.get("language") for unit in units if unit.get("language")})
    harness_language = "python" if "python" in languages else ("node" if "javascript" in languages else "python")
    edges = dataflow.get("edges", [])
    outgoing = defaultdict(list)
    for edge in edges:
        if edge.get("from") and edge.get("to"):
            outgoing[edge["from"]].append(edge["to"])

    levels = ["L0_contract", "L1_slice", "L2_smoke", "L3_nonfunctional"]
    matrix_units: List[Dict[str, Any]] = []

    artifact_sets = {
        "L0_contract": ["forgescaffold.system_catalog.json"],
        "L1_slice": ["forgescaffold.dataflow_map.json"],
        "L2_smoke": ["forgescaffold.test_matrix.yaml"],
        "L3_nonfunctional": [],
    }

    for unit in units:
        unit_id = unit.get("id")
        criteria = [
            f"Unit metadata present for {unit_id}",
            f"Linked flows: {len(outgoing.get(unit_id, []))}",
        ]
        tests: List[Dict[str, Any]] = []
        for level in levels:
            tests.append({
                "id": f"{unit_id}.{level}",
                "level": level,
                "command": build_command(unit, level),
                "artifacts_expected": artifact_sets.get(level, []),
            })
        matrix_units.append({
            "unit_id": unit_id,
            "type": unit.get("type"),
            "path": unit.get("path"),
            "success_criteria": criteria,
            "tests": tests,
        })

    harness_result = write_harness(sandbox, harness_language)

    payload = {
        "project_id": project_context["project_id"],
        "levels": levels,
        "units": matrix_units,
    }

    yaml_output = yaml.safe_dump(payload, sort_keys=False)
    artifact_path = sandbox.publish_text(
        "forgescaffold.test_matrix.yaml",
        "test_matrix.yaml",
        yaml_output,
        schema="forgescaffold.test_matrix",
    )

    return {
        "status": "SUCCEEDED",
        "outputs": {
            "forgescaffold.test_matrix.yaml": {"path": artifact_path},
            "forgescaffold.test_harness.manifest.json": {"path": harness_result["manifest_path"]},
        },
        "metrics": {"unitTests": len(matrix_units)}
    }
